# Generated by Django 4.0 on 2021-12-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('second_name', models.CharField(max_length=70)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=70)),
                ('role', models.CharField(max_length=70)),
                ('pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.job')),
            ],
        ),
    ]
